allowBuilds:
  '@firebase/util': false
  protobufjs: false
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.16 || 57.0.21'
  - '@expo/config@57.0.8'
  - '@expo/fingerprint@0.20.8 || 0.20.12'
  - '@expo/inline-modules@0.1.6'
  - '@expo/log-box@57.0.3'
  - '@expo/metro-runtime@57.0.11 || 57.0.15'
  - expo-asset@57.0.12 || 57.0.16
  - expo-constants@57.0.12 || 57.0.17
  - expo-router@57.0.14 || 57.0.18
  - expo-splash-screen@57.0.7
  - expo@57.0.14 || 57.0.19
  - lucide-react-native@1.38.0
  - '@expo/router-server@57.0.9'
  - babel-preset-expo@57.0.10
  - expo-font@57.0.3
  - expo-modules-core@57.0.15
  - expo-modules-jsi@57.0.7
  - '@expo/ui@57.0.15'
  - expo-image@57.0.4
  - expo-linking@57.0.9
  - expo-secure-store@57.0.3
